test:
  - test/**/*

documentation:
  - www/**/*
  - ./**/*.md

providers:
  - src/providers/**/*
  - www/docs/configuration/providers.md
  - test/integration/**/*

adapters:
  - src/adapters/**/*
  - www/docs/schemas/adapters.md

databases:
  - www/docs/schemas/*.md
  - test/docker/databases/**/*
  - www/docs/configuration/databases.md
  - test/fixtures/**/*

core:
  - src/**/*

style:
  - src/css/**/*

client:
  - src/client/**/*
  - www/docs/getting-started/client.md

pages:
  - src/server/pages/**/*
  - www/docs/configuration/pages.md